# Generated by Django 5.1.2 on 2024-10-31 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pokemon_imagenes')),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
