# Generated by Django 5.1.2 on 2024-10-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='first_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='last_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
