# Generated by Django 5.1.2 on 2024-10-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosextra_first_name_datosextra_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Mujer'), ('M', 'Hombre')], max_length=1, null=True),
        ),
    ]
