# Generated by Django 5.1.2 on 2024-10-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_datosextra_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
