# Generated by Django 5.1.2 on 2024-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_datosextra_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='first_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='gender',
            field=models.CharField(choices=[('F', 'Mujer'), ('M', 'Hombre')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='last_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
